### ISSUE TITLE
Can you add a funcion to block an specific user but not all reposts?

### ISSUE THREAD

**Issue by JacksonSteel** [apsun/sc-repost-blocker#3]
Can you add a funcion to block an specific user but not all reposts?

**Comment by apsun** [comment]
No sorry, that would add a lot of complexity to the addon (for example, we would have to store a list of users, meaning we would need a mechanism to save and load preferences, which means adding communication between the content script and the background script, etc.). Have you tried using SoundCloud's built in block function? Based on my understanding that should prevent you from seeing their tracks.

**Comment by JacksonSteel** [comment]
> No sorry, that would add a lot of complexity to the addon (for example, we would have to store a list of users, meaning we would need a mechanism to save and load preferences, which means adding communication between the content script and the background script, etc.). Have you tried using SoundCloud's built in block function? Based on my understanding that should prevent you from seeing their tracks.

No, it can't do that. Why need the communication? Can't just search every specific div and class, and if that div includes a div with the text(artist name), then remove the searched div(element)? In just content.js

**Comment by apsun** [comment]
Where would the list of artist names to block come from?

**Comment by JacksonSteel** [comment]
> Where would the list of artist names to block come from?

Artists I don't wanna see, but their tracks are reported by artists I followed

**Comment by apsun** [comment]
> Artists I don't wanna see

This is the problem, how can you define and edit this list in a way that will be saved persistently?

Not saying this can't be done, but I don't think this usecase justifies the amount of work needed to build it. It sounds more suitable (and honestly probably would be faster) to just build a separate add-on instead of bolting this on to the existing logic. You are welcome to use the code from this project as a base.

**Comment by JacksonSteel** [comment]
> > Artists I don't wanna see
> 
> This is the problem, how can you define and edit this list in a way that will be saved persistently?
> 
> Not saying this can't be done, but I don't think this usecase justifies the amount of work needed to build it. It sounds more suitable (and honestly probably would be faster) to just build a separate add-on instead of bolting this on to the existing logic. You are welcome to use the code from this project as a base.

Save in a txt or json or tell the users where to enter names in the code

**Comment by apsun** [comment]
> Save in a txt

Scripts cannot read arbitrary files, so this doesn't work unfortunately.

> tell the users where to enter names in the code

Since you're fine with editing the code as the configuration method, you can already do this. Just add this:
```
if (new Set([
    "blocked_username1",
    "blocked_username2",
    // ... etc
]).has(item["track"]["user"]["username"])) {
    continue;
}
```
before this line:

https://github.com/apsun/sc-repost-blocker/blob/01733cc05458372e4929625555c5cbf97c1439eb/content.js#L8

**Comment by JacksonSteel** [comment]
> > Save in a txt
> 
> Scripts cannot read arbitrary files, so this doesn't work unfortunately.
> 
> > tell the users where to enter names in the code
> 
> Since you're fine with editing the code as the configuration method, you can already do this. Just add this:
> 
> ```
> if (new Set([
>     "blocked_username1",
>     "blocked_username2",
>     // ... etc
> ]).has(item["track"]["user"]["username"])) {
>     continue;
> }
> ```
> 
> before this line:
> 
> https://github.com/apsun/sc-repost-blocker/blob/01733cc05458372e4929625555c5cbf97c1439eb/content.js#L8

Do I need to edit this?
item["track"]["user"]["username"]

And do I need to remove yellow cloud chrome extension first?

oh wait, this can only be on firefox?

>Scripts cannot read arbitrary files

really? javascript can't do this?
