### ISSUE TITLE
How to install version 2.1

### ISSUE THREAD

**Issue by rdlnz** [apsun/sc-repost-blocker#5]
Is there an installable version of 2.1 somewhere? https://addons.mozilla.org/en-US/firefox/addon/soundcloud-repost-blocker/ only has version 2.0.

Thanks.

**Comment by apsun** [comment]
Sorry for the late response - I was intending on adding more changes to 2.1 but ended up forgetting about it.

I've uploaded the current extension as-is to the Firefox addons store as version 2.1.
